name: Test

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  test-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - uses: luizm/action-sh-checker@v0.8.0
        env:
          SHFMT_OPTS: -i 2 -ci -s -d
      - run: make test
      - run: make build Search2Clip
